export const items = [
  {name: 'Campagne', price: 2.5, quantity: 0},
  {name: 'Complet', price: 2.5, quantity: 0},
  {name: 'Intégral', price: 2.5, quantity: 0},
  {name: 'Graines', price: 3.1, quantity: 0},
  {name: 'Noisettes... Raisin', price: 3.7, quantity: 0},
  {name: 'Khorasan', price: 3.6, quantity: 0},
  {name: 'Figues', price: 3, quantity: 0},
  {name: 'Noix', price: 3.5, quantity: 0},
  {name: 'Sarrasin', price: 3.8, quantity: 0},
  {name: 'Avoine', price: 2.8, quantity: 0},
  {name: 'Pavé', price: 3.5, quantity: 0},
  {name: 'Épeautre 1kg', price: 5.2, quantity: 0},
  {name: 'Seigle', price: 2.8, quantity: 0},
  {name: '5 Céréales', price: 3, quantity: 0},
  {name: 'Baguette', price: 1.3, quantity: 0},
  {name: 'Brioche', price: 5.4, quantity: 0},
  {name: 'Griaude', price: 6.5, quantity: 0},
  {name: 'Pain de mie', price: 2.9, quantity: 0},
  {name: 'Cake fruits', price: 5.4, quantity: 0},
  {name: "Pain d'épices", price: 5, quantity: 0},
  {name: 'Croissant', price: 1.1, quantity: 0},
  {name: 'Pain chocolat', price: 1.2, quantity: 0},
  {name: 'Feuilleté chèvre', price: 2.5, quantity: 0},
]
